Signature
rix-fr/rix pull request #4
Opened 2022-03-17 08:30 UTC by sludovicdelys

This PR handles the email signature of Rix members 🐺

2022-03-18 15:47 UTC, ogizanagi commented
To rebase ! Ready ?

2022-03-21 09:51 UTC, ameliedefrance requested changes

2022-03-21 09:51 UTC, ameliedefrance commented on templates/team/mail_signature.html.twig
> +                <img src="{{ absolute_url(asset('build/images/logos/logo-signature.png')) }}" alt="logo rix" width="68" height="120" style="width: 70px; height: 125px">
Ici on n'a pas les mêmes dimensions dans l'attribut `width` et `height` et dans le style. On garde 68x120px

2022-03-21 09:57 UTC, ameliedefrance commented
@sludovicdelys une fois que tu auras fait la modif sur le logo tu pourras tester la signature. 

1. Modifie ta signature Gmail avec celle de Flo.
2. Envoie toi un email test sur ton adresse Gmail et sur ton adresse Outlook (je veux bien une copie à amelie.defrance@elao.com et amelie.defrance.elao@outlook.fr). Check sur Chrome et sur Apple Mail. Check aussi sur ton téléphone.
3. Si ça s'est bien passé recommence avec la signature de Guewen qui comporte un numéro de tel supplémentaire. Pareil j'veux bien une copie du mail.

2022-03-21 15:37 UTC, sludovicdelys commented
@ameliedefrance J'ai tester les signatures de mail pour Flo et Guewen, ça à l'air de bien marcher. Dit moi si de ton côté tout se passe bien.
J'ai juste remarquer que en version mobile, le numéro de téléphone est surligné en bleu pour que l'utilisateur puisse directement appeler le numéro. Il y a quelque chose qu'on peut faire pour ça ? 
![IMG_1149](https://user-images.githubusercontent.com/74900669/159296169-28318ffc-6509-404f-b3d8-b24d7412644e.jpg)

2022-03-22 07:32 UTC, ameliedefrance commented
C'est pas grave le soulignement on laisse, par contre ce qui l'est c'est la cassure de l'adresse mail parce que la signature est trop longue. Tu peux diminuer la longueur et re-tester sur mobile avec "guewen.faivre@rix.com" (plus long que le nom de Flo)

2022-03-22 10:15 UTC, ameliedefrance approved these changes
Perfect ✨

2022-03-23 08:41 UTC, merged