Blog article
rix-fr/rix pull request #67
Opened 2022-09-28 15:47 UTC by sludovicdelys

2022-10-20 15:23 UTC, ameliedefrance commented on assets/scss/components/_table-of-content.scss
> +  padding: 29px 0 31px 65px;
Idem sur ces paddings, ils ne semblent pas venir de la maquette 

<img width="176" alt="Capture d’écran 2022-10-20 à 17 12 30" src="https://user-images.githubusercontent.com/25897625/196988390-947164ce-1cfa-4207-b88b-fbb48b48ee4b.png">

```suggestion
padding: 30px 45px;
```

2022-10-21 06:59 UTC, sludovicdelys commented on assets/scss/components/_table-of-content.scss
> +  padding: 29px 0 31px 65px;
Je me suis permise d'augmenter un peu la marge de gauche, car j'ai remarquer que le padding s'applique après la numérotation dans l'inspecteur du navigateur

 ![Capture d’écran 2022-10-21 à 08 53 05](https://user-images.githubusercontent.com/74900669/197131841-20f7f1ca-cefc-4b0d-bf8d-c2fee8bf42c9.png)

Je vais néanmoins commiter ta suggestion `padding: 30px 45px;`

2022-10-21 07:34 UTC, sludovicdelys commented on assets/scss/components/_article-footer.scss
> +    width: 30%;
Merci pour tes retours 🥋

Je suis repassée sur mon code et j'ai appliquer un `width: calc(100% / 3);` sur `author`. 
Ce qui fait que pour avoir trois auteurs sur une même row je suis repassée a une `margin-bottom: 23px;`
Et du coup j'ai plus besoin de ce code: 

```
&:nth-of-type(3n+1) {
      margin-left: 0;
    }

    &:nth-of-type(3n+3) {
      margin-right: 0;
    }
```

Est-ce que le fait que les `author`s soient plus grand que leur contenu est bloquant ? 

![Capture d’écran 2022-10-21 à 09 17 53](https://user-images.githubusercontent.com/74900669/197136251-13f74cbc-03db-49a2-b365-9f0ecc51d656.png)

2022-10-21 13:24 UTC, ameliedefrance requested changes

2022-10-21 13:24 UTC, ameliedefrance commented on assets/scss/components/_table-of-content.scss
> +  padding: 29px 0 31px 65px;
Pas de souci à adapter en effet, ma remarque c'était juste de dire qu'il fallait récupérer les bonnes marges depuis la maquette.

2022-10-21 13:24 UTC, ameliedefrance commented on assets/scss/components/_article-author.scss
> +@use '../abstracts' as *;
Cette feuille de style est utilisée ?

2022-10-21 13:24 UTC, ameliedefrance commented on assets/scss/components/_brick.scss
> +@use '../abstracts' as *;
Ce composant brick je l'avais créé sur elao parce qu'on avait des tas de blocs différents qui s'assemblaient jamais pareil. Je suis pas certaine qu'il soit utile sur Rix si c'est juste pour faire un bloc "commentaire" et un block "faire une PR sur Github"

2022-10-21 13:24 UTC, ameliedefrance commented on assets/scss/components/_brick.scss
> +@use '../abstracts' as *;
Tu devrais plutôt créer un même composant `comment` pour ça et tout mettre dedans.

2022-10-21 13:24 UTC, ameliedefrance commented on assets/scss/style.scss
> +@use "components/_kudo";
Supprimer

2022-10-21 13:24 UTC, ameliedefrance commented on assets/scss/style.scss
> +@use "components/_brick";
Regrouper les 3 composants `brick` en un seul `comment`

2022-10-21 13:31 UTC, ameliedefrance requested changes

2022-10-21 13:31 UTC, ameliedefrance commented on assets/scss/pages/_page-article.scss
> +    background-image: url('../../images/blog/pine_trees_background.jpg') !important;
C'est la même image que tu avais mis dans la bannière de l'index du blog ? Même remarque qu'à l'époque : elle est bcp trop grande et bcp trop lourde (presque 6 MB 😱). Supprime cette image dans le projet, et ici remplace la par celle qu'on avait créée qui est + petite et 6 fois moins lourde.

```suggestion
    background-image: url('../../images/blog/background.jpg') !important;
```

2022-10-21 13:31 UTC, ameliedefrance commented on assets/scss/pages/_page-article.scss
> +    background-image: url('../../images/blog/pine_trees_background.jpg') !important;
Indépendamment de ça, notre norme pour le nommage des images c'est les - et pas les _ (`pine_trees_background` -> `pine-trees-background`)

2022-10-21 13:31 UTC, ameliedefrance commented on assets/scss/pages/_page-article.scss
> +      background-image: url('../../images/case-studies/header_shape.svg');
Same ici 
```suggestion
      background-image: url('../../images/case-studies/header-shape.svg');
```

2022-10-21 13:40 UTC, ameliedefrance commented
Il manque le style des `admonition` aussi, tu peux aller t'inspirer de ce qui est sur le blog elao

![Capture d’écran 2022-10-21 à 15 39 33](https://user-images.githubusercontent.com/25897625/197209694-22dd2735-4a9c-4909-804a-8681532c7e0f.png)

2022-10-21 14:08 UTC, sludovicdelys commented on assets/scss/components/_article-author.scss
> +@use '../abstracts' as *;
Oops ! En effet plus besoin de `article-author`. Merci !

2022-11-02 15:30 UTC, ameliedefrance approved these changes
Merci @sludovicdelys

2022-11-02 15:30 UTC, merged