Page error
rix-fr/rix pull request #79
Opened 2022-11-03 10:44 UTC by sludovicdelys

[URL](http://localhost:8000/404.html)

2022-11-03 13:24 UTC, ogizanagi approved these changes

2022-11-03 13:24 UTC, ogizanagi commented on assets/scss/components/_banner-error.scss
> +    margin-right: 60px;
Ce margin-right me paraît trop gros, ça me fait bizarre de voir autant d'espace entre ces 2 boutons, non ?

2022-11-03 13:33 UTC, sludovicdelys commented on assets/scss/components/_banner-error.scss
> +    margin-right: 60px;
On a pas de maquette, je le fais un peu à l'oeil 🔎 je peux mettre un petit `30px ou 45px`.

2022-11-03 13:38 UTC, ameliedefrance requested changes

2022-11-03 13:38 UTC, ameliedefrance commented on assets/scss/components/_banner-error.scss
> +.banner-error {
[naming] `banner` a déjà une signification dans l'inté Rix, c'est le composant qui passe derrière le biseau sur chaque page et qui comporte l'image de background. Il vaut mieux trouver un autre nom ici pour éviter les confusions. `error` c'est déjà bien 👍

2022-11-03 13:38 UTC, ameliedefrance commented on assets/scss/components/_banner-error.scss
> +  border: solid 1px $color-border;
[design] pas convaincue qu'on ait besoin de créer un cartouche ici qui alourdit et qui donne un côté un peu vieillot. Tu peux supprimer le margin, le padding, le background, le border.

2022-11-03 13:38 UTC, ameliedefrance commented on assets/scss/components/_banner-error.scss
> +  font-size: toRem(36px);
[cohérence du CSS] Pourquoi surcharger le style du h1 qui est sensé être correct sur chaque page ? Tu peux supprimer le margin et la font-size.

2022-11-03 13:38 UTC, ameliedefrance commented on assets/scss/components/_banner-error.scss
> +    line-height: 1.6;
```suggestion
  font-size: toRem(53px);
```

2022-11-03 13:38 UTC, ameliedefrance commented on assets/scss/components/_banner-error.scss
> +.banner-error__content {
[Design] ce bloc et cette classe ne me semblent pas très utiles : d'un point de vue design, pourquoi surcharger le `margin-bottom` que l'on applique partout sur les `p` et donc casser la cohérence que l'on a sur le site ? Tu peux supprimer tout le `banner-error__content`

2022-11-03 13:38 UTC, ameliedefrance commented on assets/scss/components/_banner-error.scss
> +.banner-error__content {
Tu peux remettre le `margin: 0 0 35px;` sur le bloc `banner-error__action` (en changeant le margin-bottom par un margin-top)

2022-11-03 13:38 UTC, ameliedefrance commented on assets/scss/pages/_page-error.scss
> +.page-error {
[organisation] Vu le peu de CSS qu'il va rester dans `banner-error` je ne suis pas convaincue que ça mérite un composant en soi. Tu peux tout remettre dans `page-error.scss`

2022-11-03 13:38 UTC, ameliedefrance commented on templates/errors/404.html.twig
> +                <p>La page que vous recherchez n'existe pas ou a été supprimée.</p>
```suggestion
                <p>La page que vous recherchez n'existe pas ou a été supprimée. <strong>Que voulez-vous faire ?</strong></p>
```

2022-11-03 13:38 UTC, ameliedefrance commented on templates/errors/404.html.twig
> +                <a href="{{ path('homepage') }}" class="button">
```suggestion
                <a href="{{ path('homepage') }}" class="button">Retourner à l'accueil</a>
```

2022-11-03 13:38 UTC, ameliedefrance commented on templates/errors/404.html.twig
> +                <a href="{{ path('blog') }}" class="button">
```suggestion
                <a href="{{ path('blog') }}" class="button">Lire nos articles</a>
```

2022-11-04 08:37 UTC, ameliedefrance approved these changes
👌

2022-11-04 08:38 UTC, merged